name: Code checks

on:
  push:
    branches: [ master ]
  pull_requests: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9, 3.10, 3.11]
    steps:
      - uses: actions/checkout@v2
      - name: Install python ${{ matrix.python-version }}
        uses: action/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install deps
          run: 
            python -m pip install --upgrade pip
            pip install -r requirements.txt
      - name: Run flake8
        run: flake8 .
      - name: Run mypy
        run: mypy . 